### ISSUE TITLE
Usage Instructions?

### ISSUE THREAD

**Issue by myabarca** [antoniorv6/SMT#1]
Hello and congratulations on this project! I was wondering if there will be any updates soon to the “how to use” section? I would like to try this model out, but not sure where to begin.

**Comment by antoniorv6** [comment]
Hi! Thank you! Instructions will come very soon to replicate the SMT experiments. We are on the way of publishing the String Quartets dataset and, with it, instructions will be available.

**Comment by antoniorv6** [comment]
Hi! I have put very basic usage instructions, as well as a link to download the datasets. I hope you can work with the current state of the repository!
