### ISSUE TITLE
Plans to publish checkpoints

### ISSUE THREAD

**Issue by xavriley** [antoniorv6/SMT#3]
Thanks for this work! I just wondered - were you planning to make any model checkpoints available? It would be helpful for people who don't have the computing resources to train the full model from scratch

**Comment by antoniorv6** [comment]
Hi! Thank you!
Yes, my plans are to (sooner than later) publish the checkpoints of the model. I will notify when done.

**Comment by xavriley** [comment]
Hi - any updates on this?

**Comment by antoniorv6** [comment]
Hi! I have been currently reworking the repository to be compatible with the HuggingFace Transformers library, so you can download and use the pretrained weights of the SMT in just a couple lines of code. We have planned the release of the weights the day of the presentation of the paper, which is September 2nd.

**Comment by antoniorv6** [comment]
Hi! The checkpoints are published. Although I need to rework the documentation to explain how to use the weights with the current code (some clarifications needed). However, if you want to try it out, you have them at your service!

**Comment by antoniorv6** [comment]
Instructions for using the weights have been uploaded! I hope everything goes ok and it does not break! Closing thread, as request is fulfilled.
