### ISSUE TITLE
error when predict with python transcribe_single_score.py

### ISSUE THREAD

**Issue by lvpchen** [antoniorv6/SMT#4]
python transcribe_single_score.py --config config/GrandStaff/CNNSMT.gin --sample_image Data/GrandStaff/grandstaff_dataset/beethoven/piano-sonatas/sonata01-1/original_m-0-5.jpg --model_weights weights/GrandStaff/CNNSMT.ckpt

Sometimes, there is an error when i run predict.

 File "SMT/model/Decoder.py", line 28, in forward
    return x + self.pe[:, :, start:start+x.size(2)].to(x.device)
RuntimeError: The size of tensor a (833) must match the size of tensor b (832) at non-singleton dimension 2
  In call to configurable 'main' (<function main at 0x7f473ff3ef70>)

**Comment by antoniorv6** [comment]
Seems that the bug is happening during prediction, probably you are putting in the decoder more tokens than it is able to produce. I will check it out once the rework of the repository has been finished.

**Comment by antoniorv6** [comment]
Closing this issue, as the whole code of the SMT has changed to be more straightforward. Please, notify me if errors happen when using this new version.
