### ISSUE TITLE
Discrepancy in Folder Structure after Extracting GrandStaff Dataset

### ISSUE THREAD

**Issue by echunun** [antoniorv6/SMT#5]
Thank you for your work on the SMT! 
When I downloaded and extracted the GrandStaff dataset from the official website (https://grfia.dlsi.ua.es/sheet-music-transformer/), the resulting folder structure was:

├── GrandStaff
│   ├── Beethoven
│   ├── chopin
│   ├── hummel
│   ├── joplin
│   ├── mozart
│   ├── scarlatti-d

According to the instructions, the folder structure should look like this:

├── data
│   ├── GrandStaff
│   │   ├── grandstaff_dataset
│   |    ├── partitions_grandstaff

Is this difference due to a document update? How can I obtain the partitions mentioned in the SMT training?

**Comment by antoniorv6** [comment]
Hi! I have been currently reworking the entire repository to ease comprehension and make weights avialable. The documentation is outdated. I will update it as soon as possible!

**Comment by antoniorv6** [comment]
Re-reading your issue, I found out that there is an error in the documentation and uploaded files. Actually, the .tgz files should be decompressed inside the, for example, `data/GrandStaff/grandstaff_dataset`. Also, I found out that partitions are not available (I think) in the .tgz file. I will try to fix this asap. If you need them urgently, please, e-mail me to send you the partition files.

**Comment by echunun** [comment]
Thank you for the clarification! I understand the issue with the documentation. I would appreciate it if you could send them to me at your convenience. This would greatly help me proceed with my work.

**Comment by echunun** [comment]
You can reach me at 
awdvgyjm@foxmail.com.
Thank you for your assistance!

**Comment by antoniorv6** [comment]
Hi! After giving it some thought, we decidied to upload the datasets to the HuggingFace Datasets library. Given this, you do not have to deal with any folder structure for geting the data, it will be just downloaded and managed by the library. If you just want to replicate experiments, just use the configuration file at your convenience (updated them to be compatible with this new approach).

**Comment by antoniorv6** [comment]
Closing also this issue, since I think that this is fixed. Please, contact me if you find any more issues!
